### ISSUE TITLE
Syntax Error: Unexpected token import('chartist')

### ISSUE THREAD

**Issue by eisenheimjelid** [creativetimofficial/vue-light-bootstrap-dashboard#14]
Hi!, i'm starting on Vuejs/Nodejs throw your template. And all is working well with my Debian/9 and Node LTS (8.9), but i want to dockerize (Docker) your code, and i'm follow this instrucctions: http://vuetips.com/use-docker-containers so i have an error:
```
> vue-light-bootstrap-dashboard@1.0.0 dev /src
> node build/dev-server.js

> Starting dev server...
 ERROR  Failed to compile with 1 errors18:27:07

 error  in ./src/components/UIComponents/Cards/ChartCard.vue

Syntax Error: Unexpected token (129:27)

  127 |   async mounted () {
  128 |     this.updateChartId()
> 129 |     const Chartist = await import('chartist')
      |                            ^
  130 |     this.$Chartist = Chartist
  131 |     this.initChart()
  132 |   }



 @ ./src/components/UIComponents/Cards/ChartCard.vue 8:0-115 9:0-128
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/Dashboard/Views/Overview.vue
 @ ./src/components/Dashboard/Views/Overview.vue
 @ ./src/routes/routes.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

> Listening at http://localhost:8080

```
Do you have some recommendation? I did find this issue https://github.com/babel/babel-loader/issues/493 and i don't have idea if is relationed.

**Comment by JefinGeorge** [comment]
ERROR  Failed to compile with 1 errors                                                                                             09:24:47

 error  in ./resources/js/components/UIComponents/Cards/ChartCard.vue

Syntax Error: Unexpected token (129:27)

  127 |   async mounted () {
  128 |     this.updateChartId()
> 129 |     const Chartist = await import('chartist')
      |                            ^
  130 |     this.$Chartist = Chartist
  131 |     this.initChart()
  132 |   }



 @ ./resources/js/components/UIComponents/Cards/ChartCard.vue 8:21-368
 @ ./node_modules/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}]],"plugins":["transform-object-rest-spread",["transform-runtime",{"polyfill":false,"helpers":false}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./resources/js/components/Dashboard/Views/Overview.vue
 @ ./resources/js/components/Dashboard/Views/Overview.vue
 @ ./resources/js/routes/routes.js
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/sass/app.scss

**Comment by edvm** [comment]
@JefinGeorge  i solved it editing ``` /resources/js/components/UIComponents/Cards/ChartCard.vue```

Just below <script> tag:
```   import Chartist from 'chartist' ``` 

And then updated the mounted() code:
```
    mounted () {
      this.updateChartId()
      this.$Chartist = Chartist
      this.initChart()
    }
```
