### ISSUE TITLE
[ERROR] Failed to compile with 3 errors

### ISSUE THREAD

**Issue by GabrielCastello** [creativetimofficial/vue-light-bootstrap-dashboard#30]
Same error bellow in two different machines, after running npm i -> npm run dev...

Tried to install core-js as suggested but the same error continues.

[ERROR] Failed to compile with 3 errors

This dependncy was not found:

* core-js/modules/es6.regexp.to-string in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/Cards/ChartCard.vue?vue&type=script&lang=js&, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/Inputs/BaseRadio.vue?vue&type=script&lang=js& and 1 other

To install it, you can run: npm install --save core-js/modules/es6.regexp.to-string

**Comment by dekadentno** [comment]
Try this:
```bash
npm install --save-dev core-js@2.6.5
```
and then run the project again with
```
npm run serve
```
