### ISSUE TITLE
wont serve on windows

### ISSUE THREAD

**Issue by questsin** [creativetimofficial/vue-light-bootstrap-dashboard#32]
$ node -v
v10.15.3
$ npm -v
6.4.1
$ vue -V
3.6.3
user@L007260 MINGW64 ~examples/dashboard (master)
$ ls
CHANGELOG.md        CONTRIBUTING.md  intelij.webpack.js  package.json  README.md  vue.config.js
CODE_OF_CONDUCT.md  documentation    LICENSE             public        src        yarn.lock

user@L007260 MINGW64 ~examples/dashboard (master)
user@L007260 MINGW64 ~examples/dashboard (master)
$ npm install
npm WARN deprecated core-js@1.2.7: core-js@<2.6.5 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of
core-js@2.
npm WARN deprecated joi@11.4.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated topo@2.0.2: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.

> yorkie@2.0.0 install  \dashboard\node_modules\yorkie
> node bin/install.js

setting up Git hooks
can't find .git directory, skipping Git hooks installation

> node-sass@4.11.0 install  \dashboard\node_modules\node-sass
> node scripts/install.js

Cached binary found at C:\Users\user\AppData\Roaming\npm-cache\node-sass\4.11.0\win32-x64-64_binding.node

> node-sass@4.11.0 postinstall \dashboard\node_modules\node-sass
> node scripts/build.js

Binary found at \dashboard\node_modules\node-sass\vendor\win32-x64-64\binding.node
Testing binary
Binary is fine
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN bootstrap@4.3.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 1275 packages from 681 contributors and audited 28494 packages in 85.657s
found 1 high severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

user@L007260 MINGW64 ~examples/dashboard (master)
$ npm run serve

> vue-light-bootstrap-dashboard@2.0.0 serve \dashboard
> vue-cli-service serve --open

 INFO  Starting development server...
 98% after emitting CopyPlugin

 ERROR  Failed to compile with 3 errors                                                                                        1:35:10 PM
This dependency was not found:

* core-js/modules/es6.regexp.to-string in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/Cards/ChartCard.vue?vue&type=script&lang=js&, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/Inputs/BaseCheckbox.vue?vue&type=script&lang=js& and 1 other
To install it, you can run: npm install --save core-js/modules/es6.regexp.to-string

**Comment by zhukoven** [comment]
I have the same issue with 3 errors while compiling.

**Comment by guamacherox** [comment]
Same issue here

**Comment by sseypt** [comment]
Same here

**Comment by Wisdom132** [comment]
what you have to do is to go to any of your previous vue project >go to the node modules folder >copy a folder title core-js,now move to creative time project >go to the node modules folder delete the core-js folder and paste the folder you copied.then run npm run dev or npm run serve

**Comment by guamacherox** [comment]
yes or simply npm install --save core-js@2.6.5 is a version issue

**Comment by ElliotPsyIT** [comment]
The error message ``This dependency was not found: core-js/modules/es6.regexp.to-string `` appear to refer to the core-js ES6 polyfill ``to-string`` not being included in the build.  The fix for me was to add that polyfill to the .babelrc file, as follows:

```
{
  "presets": [
    [
      "@vue/app",
      {
        "polyfills": ["es7.object.entries", "es6.promise", "es6.regexp.to-string"]
      }
    ]
  ]
}
```
