### ISSUE TITLE
Project start problem

### ISSUE THREAD

**Issue by VIRGO96** [creativetimofficial/vue-light-bootstrap-dashboard#35]
![systemlists](https://user-images.githubusercontent.com/20814233/66103131-3400c480-e5ce-11e9-9c7b-d09ed018df86.PNG)
When i npm run dev it after npm i it gives npm install --save core-js/modules/es6.regexp.to-string this dependency is missing and when i try to install it says Could not install from "core-js\modules\es6.regexp.to-string" as it does not contain a package.json file kindly guide me whats wrong thanks

**Comment by williamz6** [comment]
replacing the core-js folder with core-js from another vue js project worked for me.

**Comment by williamz6** [comment]
what you have to do is to go to any of your previous vue project >go to the node modules folder >copy a folder title core-js,now move to creative time project >go to the node modules folder delete the core-js folder and paste the folder you copied.then run npm run dev or npm run serve

**Comment by mrichman** [comment]
@williamz6 That's a terrible long-term solution. This project should build out of the box. Is this project abandoned?

**Comment by jhonnattan123** [comment]
in .babelrc add
`"useBuiltIns": "entry"`

![image](https://user-images.githubusercontent.com/31730855/95935158-fae65d00-0da8-11eb-826b-002f90801288.png)
