### ISSUE TITLE
This dependency was not found:

### ISSUE THREAD

**Issue by estelle15000** [creativetimofficial/vue-light-bootstrap-dashboard#38]
This dependency was not found:

* core-js/modules/es6.regexp.to-string in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/Cards/ChartCard.vue?vue&type=script&lang=js&, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/Inputs/BaseCheckbox.vue?vue&type=script&lang=js& and 1 other

To install it, you can run: npm install --save core-js/modules/es6.regexp.to-string

**Comment by nicolas15000** [comment]
C:\UwAmp\www\vue-light-bootstrap-dashboard-master>npm install --save core-js/modules/es6.regexp.to-string
npm ERR! code ENOLOCAL
npm ERR! Could not install from "core-js\modules\es6.regexp.to-string" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\nicolas\AppData\Roaming\npm-cache\_logs\2019-11-01T08_13_32_419Z-debug.log

**Comment by donohutcheon** [comment]
I get this too - on Linux Ubuntu 18.04; Node v10.16.3

**Comment by donohutcheon** [comment]
I added core-js to package.json and it worked.
```
diff --git a/package.json b/package.json
index 2131df2..e83706e 100644
--- a/package.json
+++ b/package.json
@@ -14,6 +14,7 @@
     "deploy": "npm run build && cd docs && npm install && npm run build && cd .. && gh-pages -d dist"
   },
   "dependencies": {
+    "core-js": "^2.6.11",
     "bootstrap": "^4.3.1",
```
The latest 3.4.8 core-js version doesn't work though, only 2.x seems to work - which is deprecated.

**Comment by tangyk** [comment]
I solved this problem by following steps.
1, run [ npm install core-js] for installing core-js of version 3.
2, change .babelrc file located at the root folder from 
{
  "presets": [
    [
      "@vue/app",
      {
        "polyfills": ["es7.object.entries", "es6.promise"]
      }
    ]
  ]
}

to 

{
  "presets": [["@vue/app", { "useBuiltIns": "entry" }]]
} 


It seems works.

**Comment by jhonnattan123** [comment]
> I solved this problem by following steps.
> 1, run [ npm install core-js] for installing core-js of version 3.
> 2, change .babelrc file located at the root folder from
> {
> "presets": [
> [
> "@vue/app",
> {
> "polyfills": ["es7.object.entries", "es6.promise"]
> }
> ]
> ]
> }
> 
> to
> 
> {
> "presets": [["@vue/app", { "useBuiltIns": "entry" }]]
> }
> 
> It seems works.

work for me
![image](https://user-images.githubusercontent.com/31730855/95935240-2a956500-0da9-11eb-9a67-7e09de15d767.png)
